### ISSUE TITLE
Unable to "keep lowest dice" - as in a roll with a disadvantage in D&D 5E

### ISSUE THREAD

**Issue by paviad** [DarthPedro/OnePlat.DiceNotation#9]
I want to be able to roll and keep n lowest rolls in this way
"2d20kl1" kl stands for keep low

**Comment by DarthPedro** [comment]
Hi paviad, thanks for the feedback. I will add the keep lowest capability to the library shortly.

**Comment by DarthPedro** [comment]
@paviad I have resolved this issue and provided notation changes to support keep lowest. The dice notation changed to p for drop x lowest dice (4d6p1), and l keeps lowest x dice (2d20l1).
